global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using Microsoft.EntityFrameworkCore;
global using Magazine.Models;
global using Magazine.Data;
global using Magazine.Interfaces;
global using System.Linq.Expressions;
global using Magazine.Repositories;
global using Microsoft.AspNetCore.Mvc;